# Generated by Django 4.0.2 on 2022-02-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
