# Generated by Django 4.0.2 on 2022-02-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_data_pokemon_nickname_pokemon_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='data',
        ),
    ]
